# The Docker image that will be used to build your app
image: python:latest
# Functions that should be executed before the build script is run
before_script:
  - apt update

pages:
  stage: deploy
  image: python:latest
  script:
    - apt install -y doxygen
    - pip install mkdocs-material mkdoxy
    - cd doc
    - mkdocs build --site-dir public
  artifacts:
    paths:
      - public
  rules:
    - if: "$CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH"
