///////////////////////////////////////////////////////////////////////////////
// This file is part of Realpaver, an interval constraint and NLP solver.    //
//                                                                           //
// Copyright (c) 2017-2022 LS2N, Nantes                                      //
//                                                                           //
// Realpaver is a software distributed WITHOUT ANY WARRANTY; read the file   //
// COPYING for information.                                                  //
///////////////////////////////////////////////////////////////////////////////

#ifndef REALPAVER_BO_NODE_HPP
#define REALPAVER_BO_NODE_HPP

#include "realpaver/IntervalRegion.hpp"
#include "realpaver/SearchNode.hpp"
#include "realpaver/Scope.hpp"

namespace realpaver {

///////////////////////////////////////////////////////////////////////////////
/// This is a node of a search tree generated by a Bound Optimization solver.
///
/// A node stores the following data:
/// - an interval region of the search space;
/// - a lower bound of the objective function in this region;
/// - an upper bound of the objective function in this region;
/// - the depth in the search tree.
///////////////////////////////////////////////////////////////////////////////
class BONode : public SearchNode {
public:
   /// Creates a node
   /// @param scope set of variables of the optimization problem
   /// @param variable representing the objective function
   /// @param reg domains of variables
   BONode(const Scope& scope, const Variable& objvar,
          const IntervalRegion& reg);

   /// Copy constructor
   BONode(const BONode& node);

   /// No assignment
   BONode& operator=(const BONode& node) = delete;

   /// Destructor
   ~BONode();

   /// @return the lower bound of the objective function
   double getLower() const;

   /// Sets the lower bound of the objective function
   /// @param val new lower bound
   void setLower(const double& val);

   /// @return the upper bound of the objective function
   double getUpper() const;

   /// Sets the upper bound of the objective function
   /// @param val new upper bound
   void setUpper(const double& val);

   /// @return the vector of domains of this
   IntervalRegion* getRegion() const;

   /// @return the scope of this
   Scope getScope() const;

   /// @return the objective variable of this
   Variable getObjVar() const;

private:
   Scope scope_;
   Variable objvar_;
   IntervalRegion* reg_;
   double lower_;
   double upper_;
};

/// Output on a stream
std::ostream& operator<<(std::ostream& os, const BONode& node);

/// Type of shared pointers on BO nodes
typedef std::shared_ptr<BONode> SharedBONode;

} // namespace

#endif
