/*------------------------------------------------------------------------------
 * Realpaver -- Realpaver is a rigorous nonlinear constraint solver based on
 *              interval computations.
 *------------------------------------------------------------------------------
 * Copyright (c) 2004-2016 Laboratoire d'Informatique de Nantes Atlantique,
 *               France
 * Copyright (c) 2017-2024 Laboratoire des Sciences du Numérique de Nantes,
 *               France
 *------------------------------------------------------------------------------
 * Realpaver is a software distributed WITHOUT ANY WARRANTY. Read the COPYING
 * file for information.
 *----------------------------------------------------------------------------*/

/**
 * @file   config.hpp
 * @brief  Configuration file
 * @author Laurent Granvilliers
 * @date   2024-4-11
 */

#ifndef REALPAVER_CONFIG_HPP
#define REALPAVER_CONFIG_HPP

// file generated by Meson
#include "realpaver/configure.hpp"

static const char REALPAVER_STRING[] = PACKAGE_STRING;
static const char REALPAVER_NAME[] = PACKAGE_NAME;
static const char REALPAVER_VERSION[] = PACKAGE_VERSION;

#undef PACKAGE_NAME
#undef PACKAGE_STRING
#undef PACKAGE_VERSION
#undef PACKAGE_TARNAME
#undef PACKAGE_URL
#undef VERSION
#undef PACKAGE_BUGREPORT

#endif
