///////////////////////////////////////////////////////////////////////////////
// This file is part of Realpaver, an interval constraint and NLP solver.    //
//                                                                           //
// Copyright (c) 2017-2022 LS2N, Nantes                                      //
//                                                                           //
// Realpaver is a software distributed WITHOUT ANY WARRANTY; read the file   //
// COPYING for information.                                                  //
///////////////////////////////////////////////////////////////////////////////

#ifndef REALPAVER_CSP_SPACE_DFS_HPP
#define REALPAVER_CSP_SPACE_DFS_HPP

#include "realpaver/CSPSpace.hpp"

namespace realpaver {

///////////////////////////////////////////////////////////////////////////////
/// This is a space generated by a branch-and-prune algorithm for solving CSPs
/// that implements a Depth-First-Search strategy.
///////////////////////////////////////////////////////////////////////////////
class CSPSpaceDFS {
public:
   /// Default constructor
   CSPSpaceDFS() = default;

   /// Default destructor
   ~CSPSpaceDFS() = default;

   /// No assignment
   CSPSpaceDFS& operator=(const CSPSpaceDFS&) = delete;

   /// Default copy constructor
   CSPSpaceDFS(const CSPSpaceDFS&) = default;

   ///@{
   /// Overrides
   size_t nbPendingNodes() const;
   SharedCSPNode getPendingNode() const;
   SharedCSPNode popPendingNode();
   void insertPendingNode(const SharedCSPNode& node);
   ///@}

private:
   std::vector<SharedCSPNode> vnode_;   // vector of pending nodes
};

} // namespace

#endif
