///////////////////////////////////////////////////////////////////////////////
// This file is part of Realpaver, an interval constraint and NLP solver.    //
//                                                                           //
// Copyright (c) 2017-2023 LS2N, Nantes                                      //
//                                                                           //
// Realpaver is a software distributed WITHOUT ANY WARRANTY; read the file   //
// COPYING for information.                                                  //
///////////////////////////////////////////////////////////////////////////////

#ifndef REALPAVER_NCSP_SPACE_DFS_HPP
#define REALPAVER_NCSP_SPACE_DFS_HPP

#include "realpaver/NcspSpace.hpp"

namespace realpaver {

///////////////////////////////////////////////////////////////////////////////
/// This is a space generated by a branch-and-prune algorithm for solving CSPs
/// that implements a Depth-First-Search strategy.
///////////////////////////////////////////////////////////////////////////////
class NcspSpaceDFS : public NcspSpace {
public:
   /// Constructor
   NcspSpaceDFS();

   /// Default destructor
   ~NcspSpaceDFS() = default;

   /// No assignment
   NcspSpaceDFS& operator=(const NcspSpaceDFS&) = delete;

   /// Default copy constructor
   NcspSpaceDFS(const NcspSpaceDFS&) = default;

   ///@{
   size_t nbSolNodes() const override;
   void pushSolNode(const SharedNcspNode& node) override;
   SharedNcspNode popSolNode() override;
   SharedNcspNode getSolNode(size_t i) const override;
   bool hasFeasibleSolNode() const override;
   size_t nbPendingNodes() const override;
   SharedNcspNode nextPendingNode() override;
   void insertPendingNode(const SharedNcspNode& node) override;
   SharedNcspNode getPendingNode(size_t i) const override;
   ///@}

private:
   std::vector<SharedNcspNode> vsol_;    // vector of solution nodes
   std::vector<SharedNcspNode> vnode_;   // vector of pending nodes
};

} // namespace

#endif
